__title__ = 'unshortenit'
__description__ = 'Unshortens ad-based shorteners and any 301 redirected urls.'
__url__ = 'https://github.com/jkehler/unshortenit'
__version__ = '0.4.0'
__author__ = 'Jeffrey Kehler'
__author_email__ = 'jeffrey.kehler@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Jeffrey kehler'
